### ISSUE TITLE
JOSS review: Can authors add more explnations regarding the the LpJML installation required to run this software package?

### ISSUE THREAD

**Issue by kanishkan91** [PIK-LPJmL/lpjmlkit#5]
Perhaps I am missing something fundamental here, but since this package requires a pre-requisite installation of LpJML, can the authors describe how the same can be installed? I agree that the model itself is probably well documented already, however can the authors link to that documenation? Particularly this may be necessary to mention in the vignettes. 

Also, how are the tests in the current package solving without a pre-installed LpJML? 

https://github.com/openjournals/joss-reviews/issues/5447

**Comment by jnnsbrr** [comment]
Dear @kanishkan91 LPJmL is only required for the LPJmLRunner part, I added a line including a link to the model INSTALL file in the start of the [LPJmLRunner Vignette](https://github.com/PIK-LPJmL/lpjmlkit/blob/051c06930a658347c72765cc03502cde17ec0bc6/vignettes/lpjml-runner.Rmd#L31)

> To install LPJmL, read the [LPJmL installation instructions](https://github.com/PIK-LPJmL/LPJmL/blob/master/INSTALL).

**Comment by kanishkan91** [comment]
Thanks. Though, regarding the question above, how are the tests passing on GitHub actions if an installation of LpJML is required? This won't hold the review back. I was just curious.

**Comment by jnnsbrr** [comment]
Ah sorry, forgot to answer on that.
No this part of the function is skipped since that would require a test instance to run LPJmL which requires a more complex setup. And since the package does not only features the LPJmLRunner but functions to work with the data on very different machines we cannot provide such a setup. But we aimed to cover as much as possible of these functions with tests :-), see for example the test coverage of [`run_lpjml()`](https://app.codecov.io/gh/PIK-LPJmL/lpjmlkit/blob/master/R%2Frun_lpjml.R) or [`submit_lpjml()`](https://app.codecov.io/gh/PIK-LPJmL/lpjmlkit/blob/master/R%2Fsubmit_lpjml.R).
